import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateAppIcons, verifyGeneratedAppIcons } from "../scripts/generate-app-icons.mjs";
import { brandIconDir, brandRuntimeAssetDir } from "../scripts/lib/brand-config.mjs";
import * as facade from "../scripts/lib/brand-config.mjs";
import * as model from "../scripts/lib/brand-model.mjs";
import * as paths from "../scripts/lib/brand-paths.mjs";
import * as artifacts from "../scripts/lib/brand-artifacts.mjs";
import * as packaging from "../scripts/lib/brand-packaging.mjs";
import * as installers from "../scripts/lib/brand-installers.mjs";

const projectRoot = process.cwd();

function fileHash(filePath) {
  return createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

function snapshotFiles(rootDir) {
  const result = new Map();
  const pending = [rootDir];
  while (pending.length > 0) {
    const current = pending.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const entryPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        pending.push(entryPath);
      } else if (entry.isFile()) {
        result.set(path.relative(rootDir, entryPath).replace(/\\/gu, "/"), fileHash(entryPath));
      }
    }
  }
  return new Map([...result.entries()].sort(([left], [right]) => left.localeCompare(right)));
}

test("icon generation is complete, isolated, recoverable, and byte-idempotent for both brands", async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "desktop-brand-icons-"));
  fs.cpSync(path.join(projectRoot, "brands"), path.join(root, "brands"), { recursive: true });
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));

  const snapshots = new Map();
  for (const brandId of ["zenmind", "cutej"]) {
    await generateAppIcons({ rootDir: root, brandId, platform: process.platform });
    await verifyGeneratedAppIcons({ rootDir: root, brandId, platform: process.platform });

    const brandBuildRoot = path.dirname(brandIconDir(root, brandId));
    const before = snapshotFiles(brandBuildRoot);
    snapshots.set(brandId, before);

    const missingPath = path.join(brandIconDir(root, brandId), "icon-64.png");
    fs.rmSync(missingPath);
    await generateAppIcons({ rootDir: root, brandId, platform: process.platform });
    assert.equal(fs.existsSync(missingPath), true, brandId + " should restore an individually missing icon");

    const recovered = snapshotFiles(brandBuildRoot);
    assert.deepEqual(recovered, before, brandId + " recovery must preserve every generated byte");
    await generateAppIcons({ rootDir: root, brandId, platform: process.platform });
    assert.deepEqual(snapshotFiles(brandBuildRoot), before, brandId + " consecutive generation must be byte-idempotent");
  }

  assert.notEqual(
    snapshots.get("zenmind").get("brand-assets/brand-icon.png"),
    snapshots.get("cutej").get("brand-assets/brand-icon.png"),
    "brand app icons must not cross-contaminate"
  );
  assert.notEqual(
    snapshots.get("zenmind").get("brand-assets/tray-icon.png"),
    snapshots.get("cutej").get("brand-assets/tray-icon.png"),
    "brand tray icons must not cross-contaminate"
  );
  assert.equal(fs.existsSync(path.join(brandRuntimeAssetDir(root, "zenmind"), "brand-icon.png")), true);
  assert.equal(fs.existsSync(path.join(brandRuntimeAssetDir(root, "cutej"), "brand-icon.png")), true);
});

test("npm build, dev, unit test, and release chains prepare icons once", () => {
  const packageJson = JSON.parse(fs.readFileSync(path.join(projectRoot, "package.json"), "utf8"));
  assert.equal(packageJson.scripts["brand:sync"], "node ./scripts/sync-brand.mjs");
  assert.equal(packageJson.scripts["brand:prepare"], "npm run brand:sync && node ./scripts/generate-app-icons.mjs");
  assert.equal(packageJson.scripts.icons, "npm run brand:prepare");
  assert.equal(packageJson.scripts.build, "npm run brand:prepare && npm run build:main:prepared && npm run build:renderer:prepared");
  assert.equal(packageJson.scripts["test:unit"].match(/brand:prepare/gu)?.length, 1);
  assert.equal(packageJson.scripts.build.match(/brand:prepare/gu)?.length, 1);

  const dev = fs.readFileSync(path.join(projectRoot, "scripts", "dev.mjs"), "utf8");
  assert.equal(dev.match(/\["run", "brand:prepare"\]/gu)?.length, 1);
  assert.doesNotMatch(dev, /generate-app-icons\.mjs/u);

  const distMac = fs.readFileSync(path.join(projectRoot, "scripts", "dist-mac.mjs"), "utf8");
  assert.doesNotMatch(distMac, /\["run", "icons"\]/u);

  const makefile = fs.readFileSync(path.join(projectRoot, "Makefile"), "utf8");
  assert.match(makefile, /^release-mac:\s*$/mu);
  assert.match(makefile, /^release-win:\s*$/mu);
  assert.match(makefile, /^release-win-docker:\s*$/mu);
});

test("brand-config façade preserves the established exports across split modules", () => {
  const modules = [model, paths, artifacts, packaging, installers];
  const establishedExports = [
    "DEFAULT_BRAND_ID",
    "SUPPORTED_LOCALES",
    "DARWIN_BUNDLE_DEVELOPMENT_REGION",
    "DARWIN_BUNDLE_LOCALIZATIONS",
    "INSTALLER_SHUTDOWN_ARG",
    "DESKTOP_PACKAGE_NAME",
    "BRAND_BUILD_ROOT_DIR",
    "BRAND_RUNTIME_ASSET_DIR_NAME",
    "BRAND_RUNTIME_ASSET_FILENAMES",
    "resolveBrandId",
    "resolveRequiredBrandId",
    "loadBrandConfig",
    "syncBrandArtifacts",
    "removeStaleRendererBuild",
    "assertBrandArtifactsConsistent",
    "electronBuilderConfigPath",
    "normalizeBrandBuildTarget",
    "brandBuildTargetKey",
    "currentBrandBuildTarget",
    "brandBuildRelativePath",
    "brandBuildRoot",
    "brandGeneratedDir",
    "brandRuntimeAssetDir",
    "brandIconDir",
    "brandInstallerDir",
    "brandResourcesDir",
    "brandRendererDir",
    "brandBundleDir",
    "brandBundleElectronDir",
    "brandStageAppDir",
    "runtimeBrandPayload",
    "copyBrandDesktopPetAssets",
    "cleanupPublicBrandIconArtifacts",
    "copyBrandRuntimeIconAssets",
    "renderRendererIndexHtml",
    "electronBuilderWindowsGuid",
    "safeRepairScriptPath"
  ];
  for (const name of establishedExports) {
    assert.equal(name in facade, true, "missing façade export " + name);
    const owner = modules.find((candidate) => name in candidate);
    if (owner) {
      assert.equal(facade[name], owner[name], "façade export must be a direct re-export: " + name);
    }
  }
  assert.ok(fs.readFileSync(path.join(projectRoot, "scripts", "lib", "brand-config.mjs"), "utf8").split("\n").length < 60);
});

test("afterPack keeps macOS icon repair isolated from unrelated packaging concerns", () => {
  const source = fs.readFileSync(path.join(projectRoot, "scripts", "after-pack.js"), "utf8");
  assert.match(source, /electronPlatformName !== "darwin"/u);
  assert.match(source, /contentAddressMacAppIcon/u);
  assert.doesNotMatch(source, /rcedit|canvas-|lproj|codesign|DESKTOP_MAC_AD_HOC_SIGN/u);
  assert.equal(fs.existsSync(path.join(projectRoot, "scripts", "fix-mac-sign.js")), false);
});
