import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { generateKeyPairSync } from "node:crypto";
import { createRequire } from "node:module";
import { createSignedRelease, verifyRelease, generateSigningKey } from "../scripts/update-signing.mjs";
import { loadBuildUpdateTrust, finalizeUpdateRelease } from "../scripts/lib/update-release.mjs";
import { verifyPublicFeed } from "../scripts/verify-update-feed.mjs";
import https from "node:https";
import { EventEmitter } from "node:events";
import { Readable } from "node:stream";
const require = createRequire(import.meta.url);
const { verifySignedManifest } = require("../src/main/modules/updates/signing.js");
test("release signing produces exact-byte signatures accepted by the client and detects changed installers", async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "release-signing-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const pair = generateKeyPairSync("ed25519");
  const trust = { keys: [{ productId: "cutej", publicKey: pair.publicKey.export({ type: "spki", format: "pem" }) }] };
  const file = path.join(root, "app.exe"); fs.writeFileSync(file, "installer");
  const input = { productId: "cutej", version: "0.5.0", artifacts: { "win32-x64": { file, url: "https://example.com/app.exe" } } };
  const directory = path.join(root, "release");
  await createSignedRelease(input, directory, { privateKey: pair.privateKey, trust });
  const envelope = { manifest: fs.readFileSync(path.join(directory, "desktop-latest.json"), "utf8"), signature: fs.readFileSync(path.join(directory, "desktop-latest.json.sig"), "utf8") };
  assert.equal(Object.hasOwn(JSON.parse(envelope.manifest), "expiresAt"), false);
  assert.equal(Object.hasOwn(JSON.parse(envelope.manifest), "releaseSequence"), false);
  assert.equal(Object.hasOwn(JSON.parse(envelope.manifest), "keyId"), false);
  assert.equal(Object.hasOwn(JSON.parse(envelope.manifest), "channel"), false);
  assert.equal(verifySignedManifest(envelope, trust, "cutej").value.version, "0.5.0");
  await verifyRelease(directory, trust, "cutej", input.artifacts);
  fs.writeFileSync(file, "tampered");
  await assert.rejects(verifyRelease(directory, trust, "cutej", input.artifacts));
  await assert.rejects(createSignedRelease(input, directory, { privateKey: pair.privateKey, trust }), /exist/i);
});
test("release builds require an explicit product-bound Ed25519 public key", t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "build-trust-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  assert.throws(() => loadBuildUpdateTrust(root, "cutej", {}, true), /public|trust/i);
  assert.equal(loadBuildUpdateTrust(root, "cutej", {}).keys.length, 0);
  const pair = generateKeyPairSync("ed25519");
  const file = path.join(root, "trust.json");
  fs.writeFileSync(file, JSON.stringify({ keys: [{ productId: "cutej", publicKey: pair.publicKey.export({ type: "spki", format: "pem" }) }] }));
  assert.equal(loadBuildUpdateTrust(root, "cutej", { DESKTOP_UPDATE_TRUST_FILE: file }, true).keys.length, 1);
  assert.throws(() => loadBuildUpdateTrust(root, "other", { DESKTOP_UPDATE_TRUST_FILE: file }, true));
});
test("packaging signs only a final artifact for the built version and embedded trust", async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "release-finalize-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const pair = generateKeyPairSync("ed25519");
  const trust = { keys: [{ productId: "cutej", publicKey: pair.publicKey.export({ type: "spki", format: "pem" }) }] };
  const bundled = path.join(root, "build/brands/cutej/bundle/dist-electron"); fs.mkdirSync(bundled, { recursive: true });
  fs.writeFileSync(path.join(bundled, "update-trust.json"), JSON.stringify(trust));
  fs.writeFileSync(path.join(root, "VERSION"), "0.5.0");
  const file = path.join(root, "dist/cutej/app.exe"); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, "final executable");
  const input = { productId: "cutej", version: "0.5.0", releaseNotes: {}, artifacts: { "win32-x64": { file, url: "https://example.com/app.exe" } } };
  const inputFile = path.join(root, "release-input.json"); fs.writeFileSync(inputFile, JSON.stringify(input));
  const privateFile = path.join(root, "key.pem"); fs.writeFileSync(privateFile, pair.privateKey.export({ format: "pem", type: "pkcs8" }));
  const trustFile = path.join(root, "trust.json"); fs.writeFileSync(trustFile, JSON.stringify(trust));
  const env = { DESKTOP_UPDATE_RELEASE_INPUT: inputFile, DESKTOP_UPDATE_PRIVATE_KEY_FILE: privateFile, DESKTOP_UPDATE_TRUST_FILE: trustFile };
  const output = await finalizeUpdateRelease(root, "cutej", "win32-x64", env);
  assert.ok(fs.existsSync(path.join(output, "desktop-latest.json.sig")));
  assert.ok(output.includes(path.join("updates", "0.5.0")));
  fs.writeFileSync(inputFile, JSON.stringify({ ...input, version: "0.6.0" }));
  await assert.rejects(finalizeUpdateRelease(root, "cutej", "win32-x64", env), /version/i);
});
test("public release verification downloads and verifies the bytes actually served", async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "public-release-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const pair = generateKeyPairSync("ed25519");
  const trust = { keys: [{ productId: "cutej", publicKey: pair.publicKey.export({ type: "spki", format: "pem" }) }] };
  const file = path.join(root, "app.exe"); fs.writeFileSync(file, "final executable");
  const directory = path.join(root, "release");
  await createSignedRelease({ productId: "cutej", version: "0.5.0", releaseNotes: {}, artifacts: { "win32-x64": { file, url: "https://example.com/app.exe" } } }, directory, { privateKey: pair.privateKey, trust });
  const metadata = fs.readFileSync(path.join(directory, "desktop-latest.json"));
  const signature = fs.readFileSync(path.join(directory, "desktop-latest.json.sig"));
  const replies = [metadata, signature, fs.readFileSync(file), metadata, signature, Buffer.from("corrupted")];
  const original = https.get; t.after(() => { https.get = original; });
  https.get = (_url, _options, cb) => {
    const req = new EventEmitter(); req.setTimeout = () => {};
    process.nextTick(() => { const res = Readable.from([replies.shift()]); res.statusCode = 200; res.headers = {}; cb(res); }); return req;
  };
  assert.equal((await verifyPublicFeed("https://example.com/latest.json", trust, "cutej")).version, "0.5.0");
  await assert.rejects(verifyPublicFeed("https://example.com/latest.json", trust, "cutej"));
});
test("key generation refuses repository paths so private keys cannot enter build archives", t => {
  const directory = path.resolve("tmp", `forbidden-signing-key-${Date.now()}`);
  t.after(() => fs.rmSync(directory, { recursive: true, force: true }));
  assert.throws(() => generateSigningKey(directory, "cutej", "test-passphrase-only"), /outside/i);
  assert.equal(fs.existsSync(directory), false);
});
