import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (...parts) => fs.readFileSync(path.join(projectRoot, ...parts), "utf8");

test("Kanban detail keeps the full cloud snapshot in shared contracts and SQLite cache", () => {
  const contracts = read("src", "shared", "contracts", "kanban.ts");
  const store = read("src", "main", "kanban-local-store.ts");
  const issueContract = contracts.slice(
    contracts.indexOf("export interface KanbanIssue {"),
    contracts.indexOf("export interface KanbanIssueInput")
  );
  assert.match(contracts, /interface KanbanCloudDetailData/);
  assert.match(contracts, /customFields\?: Record<string, unknown>/);
  assert.match(contracts, /parentIssueId\?: string \| null/);
  assert.match(contracts, /runResultMessage\?: string \| null/);
  assert.match(contracts, /projectVersion\?: string \| null/);
  assert.match(contracts, /dueDate\?: string \| null/);
  assert.match(contracts, /componentKeys: string\[\]/);
  assert.match(contracts, /cloudDetails\?: KanbanCloudDetailData/);
  assert.doesNotMatch(issueContract, /reviewerId|reviewRequired/);
  assert.match(store, /DETAIL_JSON_ TEXT NOT NULL DEFAULT '\{\}'/);
  assert.match(store, /CREATE TABLE IF NOT EXISTS kanban_cloud_detail_cache/);
  assert.match(store, /storeCloudDetailData\(db, currentUser, snapshot, revision\)/);
  assert.match(store, /const SYNC_CACHE_SCHEMA_VERSION = 1/);
  assert.match(store, /COMPONENTS_JSON_ TEXT NOT NULL DEFAULT '\[\]'/);
  assert.match(store, /migrateDesktopKanbanIssueDetailJson\(db\)/);
  assert.doesNotMatch(store, /(?:rawIssue|input|issue|row)\.(?:reviewerId|reviewRequired|reviewer_id|review_required)/);
});

test("Kanban detail opens independently from create and preserves the cloud read-only boundary", () => {
  const page = read("src", "renderer", "pages", "kanban", "KanbanPage.tsx");
  const detail = read("src", "renderer", "pages", "kanban", "KanbanIssueDetailDialog.tsx");
  const styles = read("src", "renderer", "styles", "kanban.css");
  const rendererIndex = read("index.html");
  const brandConfig = read("scripts", "lib", "brand-config.mjs");
  const packageManifest = JSON.parse(read("package.json"));
  assert.match(page, /setModal\(\{ mode: "create" \}\)/);
  assert.match(page, /const openEditModal = useCallback\(\(issue: KanbanIssue\) => \{[\s\S]{0,180}setDetailIssueId\(issue\.id\)/);
  assert.match(page, /<KanbanIssueDetailDialog/);
  assert.match(page, /onSave=\{\(draft\) => saveIssueDetail\(detailIssue, draft\)\}/);
  assert.match(page, /if \(!kanbanApi \|\| !canEditKanbanIssueBody\(issue\)\)/);
  assert.doesNotMatch(detail, /DetailTab|activeTab|showGroup|kanban-detail-tabs/);
  assert.match(detail, /useState\(!isCloud && Boolean\(initialEditStatus\)\)/);
  assert.match(detail, /P0: "kanban\.priority\.p0"[\s\S]{0,180}P3: "kanban\.priority\.p3"/);
  assert.match(detail, /kanban\.importance\.\$\{issue\.severity\}/);
  assert.match(detail, /id="kanban-detail-title"[\s\S]{0,160}disabled=\{!editing\}/);
  assert.equal(packageManifest.dependencies["react-markdown"], "^10.1.0");
  assert.equal(packageManifest.dependencies["remark-gfm"], "^4.0.1");
  assert.equal(packageManifest.dependencies.mermaid, "^11.16.1");
  assert.match(detail, /editing \? <>[\s\S]{0,900}<textarea ref=\{descriptionEditorRef\}[\s\S]{0,500}<MarkdownPreview value=\{draft\.description\}/);
  assert.match(detail, /<MarkdownPreview value=\{comment\.body\} variant="comment" t=\{t\} \/>/);
  assert.match(detail, /<ReactMarkdown[\s\S]{0,260}remarkPlugins=\{\[remarkGfm\]\}[\s\S]{0,120}skipHtml[\s\S]{0,120}urlTransform=\{transformMarkdownUrl\}/);
  assert.ok(detail.includes('/^data:image\\/(?:gif|jpeg|png|svg\\+xml|webp);base64,/iu'));
  assert.match(detail, /return defaultUrlTransform\(url\)/);
  assert.match(rendererIndex, /img-src 'self' data: https:/);
  assert.match(brandConfig, /img-src 'self' data: https:/);
  assert.doesNotMatch(rendererIndex, /img-src[^";]*http:/);
  assert.match(detail, /language-mermaid[\s\S]{0,260}<MermaidDiagram source=\{source\} t=\{t\}/);
  assert.match(detail, /import\("mermaid"\)/);
  assert.match(detail, /securityLevel: "strict"[\s\S]{0,160}suppressErrorRendering: true[\s\S]{0,160}maxTextSize: 50_000/);
  assert.match(detail, /mermaid\.parse\(source, \{ suppressErrors: true \}\)/);
  assert.match(detail, /kanban\.detail\.mermaidRenderFailed[\s\S]{0,180}<pre><code className="language-mermaid">\{source\}/);
  assert.doesNotMatch(detail, /<span>\{comment\.body\}<\/span>/);
  assert.match(detail, /!isCloud \? \([\s\S]{0,220}<button[\s\S]{0,180}setEditing\(true\)/);
  assert.match(detail, /if \(await onSave\(draft\)\) setEditing\(false\)/);
  assert.match(detail, /kanban\.detail\.cloudReadonly/);
  assert.match(detail, /issue\.issueTypeKey \?\? issue\.typeId \?\? ""/);
  assert.doesNotMatch(detail, /issue\.issueTypeKey \?\? issue\.typeId \?\? "task"/);
  assert.match(detail, /automationCron: issue\.automationCron \?\? ""/);
  assert.match(detail, /automationTimezone: issue\.automationTimezone \?\? ""/);
  assert.doesNotMatch(detail, /automation(?:Cron|Timezone): issue\.automation(?:Cron|Timezone) \?\? "(?:0 9 \* \* \*|Asia\/Shanghai)"/);
  assert.match(detail, /issue\.projectName \|\| issue\.projectId \|\| "—"/);
  assert.doesNotMatch(detail, /issue\.projectName \|\| t\("kanban\.projectFilter\.all"\)/);
  assert.match(detail, /label=\{t\("kanban\.form\.version"\)\}[\s\S]{0,300}<select value=\{draft\.projectVersion\}/u);
  assert.match(detail, /kanban\.form\.dueDate[\s\S]*kanban\.form\.components[\s\S]*kanban\.form\.originalEstimate/);
  assert.match(detail, /kanban\.detail\.dueRisk[\s\S]*kanban\.detail\.securityLevel/);
  assert.match(page, /issue\.projectVersion\?\.trim\(\) \? t\("kanban\.card\.version"/u);
  assert.match(page, /<select[\s\S]{0,180}value=\{form\.projectVersion\}/u);
  assert.doesNotMatch(page, /issue\.dueAt|value=\{form\.version\}/);
  assert.doesNotMatch(detail, /issue\.reviewerId|kanban\.detail\.reviewer/);
  assert.doesNotMatch(detail, /kanban-detail-footer|const editing = !isCloud/);
  assert.match(detail, /className="kanban-detail-window-actions"[\s\S]{0,700}kanban\.chat\.view[\s\S]{0,900}kanban\.detail\.editIssue[\s\S]{0,500}kanban-detail-close/);
  assert.match(detail, /chatEmbedPath \? \([\s\S]{0,300}kanban-detail-chat-layout[\s\S]{0,2500}<ServiceWebviewSurface[\s\S]{0,500}surfaceOwnershipActive=\{false\}[\s\S]{0,500}surfaceId="agent-webclient-kanban-chat"/);
  assert.match(detail, /chatEmbedPath \? t\("kanban\.chat\.viewIssue"\) : t\("kanban\.chat\.view"\)/);
  assert.match(detail, /disabled=\{!chatEmbedPath && !latestOpenableIssueChat\}/);
  assert.match(detail, /return \[\.\.\.chatsByChatId\.values\(\)\]\.sort\(compareIssueChatTime\)/);
  assert.match(detail, /const latestOpenableIssueChat = openableIssueChats\.at\(-1\)/);
  assert.match(detail, /className="kanban-detail-chat-list"[\s\S]{0,1800}issueChatItems\.map[\s\S]{0,1200}onClick=\{\(\) => openChat\(chat\)\}/);
  assert.match(detail, /chat\.local && chat\.state === "active" && Boolean\(chat\.agentKey\)/);
  assert.match(styles, /\.kanban-detail-chat-layout\s*\{[\s\S]{0,260}grid-template-columns:\s*220px minmax\(0, 1fr\)/);
  assert.match(styles, /\.kanban-detail-window-actions \.kanban-detail-secondary-button:disabled\s*\{\s*cursor:\s*not-allowed/);
  assert.match(page, /onOpenChat=\{\(chatId, agentKey\) => openAssistantIssueChat\(detailIssue, chatId, agentKey\)\}/);
  assert.match(page, /return createAgentWebclientRoute\(\{ agentKey, chatId \}\)/);
  assert.doesNotMatch(page, /setDetailIssueId\(null\);[\s\S]{0,100}navigate\(createAgentWebclientRoute\(\{ agentKey, chatId \}\)\)/);
  assert.doesNotMatch(detail, /"(?:issue\.(?:transition|assignRun|dispatchDesktop)|review\.comment\.|issueLabel\.|issue\.dependency\.)/);
});

test("Kanban cards use the Website hierarchy without hover actions", () => {
  const page = read("src", "renderer", "pages", "kanban", "KanbanPage.tsx");
  const styles = read("src", "renderer", "styles", "kanban.css");
  const card = page.slice(page.indexOf("const IssueCardContent"), page.indexOf("function IssueCardSignalIcon"));
  const operational = page.slice(
    page.indexOf("function getIssueCardOperationalStatePresentation"),
    page.indexOf("function getKanbanEmptyHint")
  );
  assert.match(page, /color: stage\?\.color\?\.trim\(\) \|\|/);
  assert.match(styles, /\.issue-card-workflow-progress\s*\{[\s\S]{0,180}height: 3px/);
  assert.match(card, /issue-card-type-corner/);
  assert.match(card, /issue-card-version/);
  assert.match(card, /issue-card-queue-rank/);
  assert.match(card, /IssueCardPriorityImportance[\s\S]*issue-card-title-text/);
  assert.match(styles, /\.issue-card-priority-importance/);
  assert.match(card, /issue-card-footer-row is-summary[\s\S]*issue-card-footer-row is-operational/);
  assert.match(page, /issue\.status !== "todo"[\s\S]{0,900}Date\.UTC\(year, month - 1, day\)/);
  assert.match(card, /issue\.dueRisk[\s\S]*DueRiskAlarmIcon/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.issue-card-due-risk \{ animation: none; \}/);
  assert.doesNotMatch(card, /issue-card-actions|issue-card-action|onOpenChat|onDelete/);
  assert.doesNotMatch(styles, /\.issue-card-actions|\.issue-card-action(?:\W)/);
  assert.match(operational, /runState === "cancelled"[\s\S]*runState === "failed"[\s\S]*awaitingConfirmation/);
  assert.doesNotMatch(operational, /kanban\.run\.running|icon: "running"/);
  assert.match(page, /type SearchFilterMenuKind = "issueType" \| "priority" \| "severity"/);
  assert.match(page, /issue\.priority \?\? "unset"[\s\S]*issueSeverity \?\? "unset"/);
  assert.match(page, /issue\.issueTypeKey \?\? issue\.typeId[\s\S]*issue\.reporterId[\s\S]*issue\.projectPath[\s\S]*\.\.\.issue\.componentKeys/);
});

test("Kanban detail keeps content on the left and all remaining issue data on the right", () => {
  const resolver = read("src", "renderer", "pages", "kanban", "issueFieldResolution.ts");
  const history = read("src", "renderer", "pages", "kanban", "issueDetailHistory.ts");
  const detail = read("src", "renderer", "pages", "kanban", "KanbanIssueDetailDialog.tsx");
  const styles = read("src", "renderer", "styles", "kanban.css");
  const enUS = read("src", "shared", "i18n", "dictionaries", "enUS.ts");
  const content = detail.slice(detail.indexOf('<main className="kanban-detail-content">'), detail.indexOf("</main>"));
  const railStart = detail.indexOf('<aside className="kanban-detail-rail"');
  const rail = detail.slice(railStart, detail.indexOf("</aside>", railStart));
  const header = detail.slice(detail.indexOf('<header className="kanban-detail-header">'), detail.indexOf('<div className="kanban-detail-body">'));
  const basic = rail.slice(rail.indexOf('sectionId="kanban-detail-basic"'), rail.indexOf('sectionId="kanban-detail-people"'));
  const people = rail.slice(rail.indexOf('sectionId="kanban-detail-people"'), rail.indexOf('sectionId="kanban-detail-related"'));
  const related = rail.slice(rail.indexOf('sectionId="kanban-detail-related"'), rail.indexOf('sectionId="kanban-detail-activity"'));
  const activity = rail.slice(rail.indexOf('sectionId="kanban-detail-activity"'), rail.indexOf('kanban-detail-readonly-note'));
  assert.match(resolver, /buildKanbanProjectDistances/);
  assert.match(resolver, /candidateRank\.specificity > currentRank\.specificity/);
  assert.match(resolver, /candidateDistance < currentDistance/);
  assert.match(resolver, /candidateRank\.dimension > currentRank\.dimension/);
  assert.match(detail, /valueType\.includes\("user"\)/);
  assert.match(detail, /valueType\.includes\("issue"\)/);
  assert.match(detail, /valueType\.includes\("select"\)/);
  assert.match(detail, /valueType === "json"/);
  assert.match(enUS, /"kanban\.detail\.basicTitle": "Basic"/);
  assert.match(history, /export function resolveKanbanIssueRuns[\s\S]*eventIssueSnapshot\(event\)[\s\S]*issue\.runId[\s\S]*return \[\.\.\.runs\.values\(\)\]/);
  assert.match(history, /status: KanbanRunState \| null/);
  assert.doesNotMatch(history, /status: (?:status|issueStatus) \|\| previous\?\.status \|\| "running"/);
  assert.match(history, /export function resolveKanbanStatusTimeline[\s\S]*eventStatusTransition\(event\)[\s\S]*fromLabel[\s\S]*toLabel[\s\S]*issue\.statusId \|\| issue\.status/);
  assert.match(history, /event\.payload\?\.summary/);
  assert.match(detail, /function DetailProperty[\s\S]{0,1600}kanban-detail-property-editor[\s\S]{0,300}kanban-detail-property-value/);
  assert.match(content, /kanban-detail-issue-heading[\s\S]*kanban\.detail\.descriptionTitle[\s\S]*kanban\.detail\.attachmentsTitle[\s\S]*kanban\.detail\.commentsTitle/);
  assert.match(header, /kanban-detail-breadcrumb[\s\S]*kanban\.detail\.cloudOrigin/);
  assert.doesNotMatch(header, /kanban-detail-kicker|DETAIL_STATUS_LABELS|DETAIL_PRIORITY_LABELS|kanban\.detail\.localOrigin/);
  assert.match(detail, /```mermaid/);
  assert.match(detail, /shell\.openExternal\(attachment\.url\)/);
  assert.doesNotMatch(detail, /description=\{t\("kanban\.detail\./);
  assert.doesNotMatch(content, /kanban\.detail\.(?:customFieldsTitle|labelsTitle|subtasksTitle|dependenciesTitle|reviewsTitle|runsTitle|activityTitle|sourceTitle)/);
  const anchor = rail.slice(rail.indexOf("kanban-detail-anchor-nav"), rail.indexOf("</nav>"));
  assert.match(anchor, /kanban\.detail\.basicTitle[\s\S]*kanban\.detail\.peopleTitle[\s\S]*kanban\.detail\.relatedTitle[\s\S]*kanban\.detail\.activityTitle/);
  assert.doesNotMatch(anchor, /kanban\.detail\.(?:scopeTitle|automationTitle|runsTitle|sourceTitle)/);
  assert.match(basic, /kanban\.detail\.issueId[\s\S]*kanban\.detail\.project[\s\S]*kanban\.detail\.workflow[\s\S]*kanban\.form\.status[\s\S]*kanban\.form\.priority[\s\S]*kanban\.detail\.severity[\s\S]*resolvedFields\.map[\s\S]*kanban\.detail\.createdAt[\s\S]*kanban\.detail\.updatedAt/);
  assert.doesNotMatch(rail, /sectionId="kanban-detail-scope"/);
  assert.match(people, /kanban\.detail\.owner[\s\S]*kanban\.detail\.executor[\s\S]*kanban\.form\.automationEnabled[\s\S]*kanban\.form\.cron/);
  assert.match(related, /kanban\.detail\.parentTitle[\s\S]*kanban\.detail\.subtasksTitle[\s\S]*kanban\.detail\.dependenciesTitle[\s\S]*kanban\.detail\.reviewsTitle[\s\S]*kanban\.detail\.runsTitle/);
  assert.match(related, /runs\.map[\s\S]*run\.resultMessage[\s\S]*run\.errorMessage/);
  assert.match(related, /run\.workerAgent \|\| "—"[\s\S]{0,100}run\.status \? <em/);
  assert.match(related, /kanban-detail-run-footer[\s\S]*kanban\.detail\.runSpent[\s\S]*formatRunDuration\(run\.startedAt, run\.finishedAt, t\)[\s\S]*kanban\.detail\.runCompletedAt[\s\S]*formatDateTime\(run\.finishedAt, locale\)[\s\S]*viewChatButton/);
  assert.doesNotMatch(related, /run\.runId|kanban\.detail\.runIdMissing|run\.stageId|run\.statusId/);
  assert.doesNotMatch(related, /run\.workerAgent \|\| agentLabel/);
  assert.doesNotMatch(related, /kanban\.detail\.activityTitle/);
  assert.match(enUS, /"kanban\.detail\.activityTitle": "Timeline"/);
  assert.match(activity, /kanban\.detail\.activityTitle[\s\S]*statusTimeline\.map[\s\S]*entry\.fromLabel[\s\S]*ArrowRightOutlined[\s\S]*entry\.toLabel/);
  assert.match(activity, /usersById\.get\(entry\.actor\)[\s\S]*kanban\.detail\.unknownActor[\s\S]*formatDateTime\(entry\.createdAt[\s\S]*debugMode && event\?\.payload[\s\S]*kanban\.detail\.eventPayload/);
  assert.doesNotMatch(activity, /kanban\.detail\.systemActor/);
  assert.match(detail, /const parentIssueId = issue\.parentIssueId\?\.trim\(\) \?\? ""/);
  assert.doesNotMatch(detail, /sectionId="kanban-detail-(?:automation|runs|source)"/);
  assert.match(detail, /useDebugMode\(\)[\s\S]*debugMode \? <DetailProperty[\s\S]*kanban\.detail\.revision/);
  assert.match(detail, /window\.electronAPI\.clipboard\.writeText\(value\)/);
  assert.match(detail, /onDoubleClick=\{copy\}/);
  assert.doesNotMatch(detail, /showCopyButton|copyButtonTitle|CopyOutlined/);
  assert.match(detail, /kanban-detail-readonly-note[\s\S]*kanban\.detail\.cloudReadonlyCompact/);
  assert.doesNotMatch(detail, /kanban-detail-readonly-banner is-rail/);
  assert.doesNotMatch(rail, /kanban\.detail\.customFieldsTitle|kanban\.detail\.noCustomFields/);
  assert.match(styles, /\.kanban-detail-dialog\s*\{[\s\S]{0,180}width: min\(1062px, calc\(90vw - 43\.2px\)\);[\s\S]{0,80}height: min\(81vh, 738px\);[\s\S]{0,80}min-height: 558px/);
  assert.match(styles, /@media \(max-width: 980px\)[\s\S]{0,180}\.kanban-detail-dialog \{ min-height: 0; \}/);
  assert.match(styles, /\.kanban-detail-layer\s*\{[\s\S]{0,760}background: rgba\(22, 29, 40, 0\.16\);[\s\S]{0,100}backdrop-filter: none/);
  assert.match(styles, /:root\[data-theme="dark"\] \.kanban-detail-layer\s*\{[\s\S]{0,760}background: rgba\(3, 5, 8, 0\.32\)/);
  assert.match(styles, /\.kanban-detail-body\s*\{[\s\S]{0,180}grid-template-columns: minmax\(0, 1fr\) 280px/);
  assert.match(styles, /\.kanban-detail-properties > div \{[^\n]*grid-template-columns: minmax\(72px, 42%\) minmax\(0, 1fr\)/);
  assert.match(detail, /function resizeTextareaToContent[\s\S]{0,320}scrollHeight \+ borderHeight/);
  assert.match(detail, /useLayoutEffect\(\(\) => \{[\s\S]{0,140}resizeTextareaToContent\(descriptionEditorRef\.current\)[\s\S]{0,80}\[draft\.description, editing\]/);
  assert.match(detail, /new ResizeObserver[\s\S]{0,360}resizeTextareaToContent\(textarea\)/);
  assert.match(detail, /<textarea ref=\{descriptionEditorRef\}/);
  assert.match(styles, /\.kanban-detail-description-editor \{[^\n]*min-height: 120px;[^\n]*overflow-y: hidden; resize: none/);
  assert.match(styles, /\.kanban-detail-description-editor\.is-editing \{ min-height: 200px; \}/);
  assert.doesNotMatch(styles, /\.kanban-detail-description-editor(?:\.is-editing)? \{[^\n]*(?<!-)height:/);
  assert.match(styles, /\.kanban-detail-title-input \{[\s\S]{0,260}font-size: clamp\(17px, 1\.35vw, 20px\)/);
  assert.match(styles, /\.kanban-detail-anchor-nav \{[\s\S]{0,100}position: sticky;[\s\S]{0,80}top: 0/);
  assert.match(styles, /\.kanban-detail-section \{[\s\S]{0,260}border: 0;[\s\S]{0,120}border-bottom: 1px solid var\(--detail-line-subtle\)/);
  assert.match(styles, /\.kanban-detail-rail \{[^\n]*border-left: 1px solid var\(--detail-line-subtle\)/);
  assert.match(styles, /\.kanban-detail-property-editor select/);
  assert.doesNotMatch(styles, /\.kanban-detail-properties > div\.is-copyable|cursor: copy/);
  assert.match(styles, /\.kanban-detail-copy-notice[\s\S]{0,220}position: absolute/);
  assert.match(styles, /\.kanban-detail-readonly-note[\s\S]{0,220}color: var\(--detail-muted\)/);
  assert.match(styles, /\.kanban-detail-run-list[\s\S]{0,120}flex-direction: column/);
  assert.match(styles, /\.kanban-detail-title-input:disabled \{[\s\S]{0,100}border-color: transparent/);
  assert.doesNotMatch(styles, /grid-template-columns: minmax\(0, 1fr\) 286px/);
  assert.doesNotMatch(styles, /\.kanban-detail-footer/);
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*?\.kanban-detail-body \{ display: block/);
  assert.match(styles, /:root\[data-theme="dark"\] \.kanban-detail-layer/);
});
