export { loadBuiltinServices } from "./builtin-loader";
export { resolveContainerEngine, runContainerEngineCommand } from "./container-engine";
export type { ContainerEngineName, ContainerEngineResolution } from "./container-engine";
export { registerServicesIpcHandlers } from "./ipc";
export { getServiceLifecycleArgsConfigPath, normalizeServiceLifecycleArgsConfig, writeServiceLifecycleArgsConfig } from "./lifecycle-args";
export { captureManagedProcessCleanupSnapshotAsync, fixShellScriptPermissions, forceCleanupManagedProcesses, getResponsiveServiceState, getServiceLogsMeta, getServiceState, importEnvZipIntoExistingRuntime, importServiceFile, initializeService, installBuiltinService, listServices, readServiceConfig, readServiceLog, restartService, runStartupPreparation, startService, stopRunningServicesForShutdown, stopService, watchServiceLog, writeServiceConfig } from "./manager";
export { resolveDesktopCapability } from "./manager/capabilities";
export { buildServiceEnv, resolveCommandBin } from "./manager/command-env";
export { windowsPowerShellPath } from "./manager/command-runner";
export { getInstallDir, getServiceLayout } from "./manager/layout";
export { isProcessRunning, listProcessTreePidsAsync, requestWindowsProcessTreeExitAsync, terminateCapturedProcessTreeAsync, terminateProcessTree } from "./manager/process-cleanup";
export { matchProcessInstallDirAsync, pidMatchesInstallDir } from "./manager/process-identity";
export { resolvePreferredAgentPlatformRuntimeRoot } from "./manager/runtime-paths";
export { delay, probeHttpUrl } from "./manager/service-probes";
export { getServicePortDefaultsConfigPath, normalizeServicePortDefaultsConfig, writeServicePortDefaultsConfig } from "./port-defaults";
export { createServicesRuntime } from "./runtime";
export { createServicesFacade } from "./facade";
export type { ServicesFacade } from "./facade";
export type { ServicesIntegrationPorts } from "./integration-ports";
export { clearServices, getAllServices, getService, registerService, unregisterService } from "./service-registry";
export { STARTUP_RESTORE_SERVICE_ORDER } from "./startup-order";
