export const EMBEDDED_CDP_GATEWAY_HOST = "127.0.0.1";
export const EMBEDDED_CDP_GATEWAY_PORT = 11789;
export const EMBEDDED_CDP_GATEWAY_URL = `http://${EMBEDDED_CDP_GATEWAY_HOST}:${EMBEDDED_CDP_GATEWAY_PORT}`;
