export const SERVICE_WEBVIEW_BRIDGE_MESSAGE_CHANNEL = "desktop:service-webview:message";
export const SERVICE_WEBVIEW_BRIDGE_DELIVER_CHANNEL = "desktop:service-webview:deliver";
export const SERVICE_WEBVIEW_BRIDGE_ROUTE_CHANNEL = "desktop:service-webview:route";
export const SERVICE_WEBVIEW_BRIDGE_ACTION_CHANNEL = "desktop:service-webview:action";
export const SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE = "desktop:service-webview:debug";

export const AGENT_APP_CLIPBOARD_REQUEST_TYPE = "desktop:agent-app-clipboard:request";
export const AGENT_APP_CLIPBOARD_RESPONSE_TYPE = "desktop:agent-app-clipboard:response";
export const DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE = "desktop:dialog:select-directory";
export const DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE = "desktop:dialog:select-directory:response";
export const DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE = "desktop:shell:open-path";
export const DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE = "desktop:shell:open-path:response";
export const DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE = "desktop:download:file";
export const DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE = "desktop:download:file:response";
export const DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE = "desktop:screenshot:capture";
export const DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE = "desktop:screenshot:capture:response";
export const PLUGIN_SETTINGS_READ_REQUEST_TYPE = "desktop:plugin-settings:read";
export const PLUGIN_SETTINGS_READ_RESPONSE_TYPE = "desktop:plugin-settings:read:response";
export const PLUGIN_SETTINGS_WRITE_REQUEST_TYPE = "desktop:plugin-settings:write";
export const PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE = "desktop:plugin-settings:write:response";
export const DESKTOP_CONTEXT_CHANGED_MESSAGE_TYPE = "desktopContextChanged";
export const DESKTOP_ROUTE_CHANGED_MESSAGE_TYPE = "desktopRouteChanged";

export const LEGACY_SERVICE_WEBVIEW_BRIDGE_MESSAGE_CHANNEL = "zenmind:service-webview:message";
export const LEGACY_SERVICE_WEBVIEW_BRIDGE_DELIVER_CHANNEL = "zenmind:service-webview:deliver";
export const LEGACY_SERVICE_WEBVIEW_BRIDGE_ROUTE_CHANNEL = "zenmind:service-webview:route";
export const LEGACY_SERVICE_WEBVIEW_BRIDGE_ACTION_CHANNEL = "zenmind:service-webview:action";
export const LEGACY_SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE = "zenmind:service-webview:debug";

export const LEGACY_AGENT_APP_CLIPBOARD_REQUEST_TYPE = "zenmind:agent-app-clipboard:request";
export const LEGACY_AGENT_APP_CLIPBOARD_RESPONSE_TYPE = "zenmind:agent-app-clipboard:response";
export const LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE = "zenmind:desktop-dialog:select-directory";
export const LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE = "zenmind:desktop-dialog:select-directory:response";
export const LEGACY_DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE = "zenmind:desktop-shell:open-path";
export const LEGACY_DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE = "zenmind:desktop-shell:open-path:response";
export const LEGACY_DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE = "zenmind:desktop-download:file";
export const LEGACY_DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE = "zenmind:desktop-download:file:response";
export const LEGACY_DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE = "zenmind:desktop-screenshot:capture";
export const LEGACY_DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE = "zenmind:desktop-screenshot:capture:response";
export const LEGACY_PLUGIN_SETTINGS_READ_REQUEST_TYPE = "zenmind:plugin-settings:read";
export const LEGACY_PLUGIN_SETTINGS_READ_RESPONSE_TYPE = "zenmind:plugin-settings:read:response";
export const LEGACY_PLUGIN_SETTINGS_WRITE_REQUEST_TYPE = "zenmind:plugin-settings:write";
export const LEGACY_PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE = "zenmind:plugin-settings:write:response";

export const SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPES = [
  AGENT_APP_CLIPBOARD_REQUEST_TYPE,
  DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE,
  DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE,
  DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE,
  DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE,
  PLUGIN_SETTINGS_READ_REQUEST_TYPE,
  PLUGIN_SETTINGS_WRITE_REQUEST_TYPE
] as const;

export const LEGACY_SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPES = [
  LEGACY_AGENT_APP_CLIPBOARD_REQUEST_TYPE,
  LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE,
  LEGACY_DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE,
  LEGACY_DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE,
  LEGACY_DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE,
  LEGACY_PLUGIN_SETTINGS_READ_REQUEST_TYPE,
  LEGACY_PLUGIN_SETTINGS_WRITE_REQUEST_TYPE
] as const;

export const SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPES = [
  AGENT_APP_CLIPBOARD_RESPONSE_TYPE,
  DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE,
  DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE,
  DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE,
  DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE,
  PLUGIN_SETTINGS_READ_RESPONSE_TYPE,
  PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE,
  DESKTOP_CONTEXT_CHANGED_MESSAGE_TYPE,
  DESKTOP_ROUTE_CHANGED_MESSAGE_TYPE
] as const;

export const LEGACY_SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPES = [
  LEGACY_AGENT_APP_CLIPBOARD_RESPONSE_TYPE,
  LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE,
  LEGACY_DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE,
  LEGACY_DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE,
  LEGACY_DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE,
  LEGACY_PLUGIN_SETTINGS_READ_RESPONSE_TYPE,
  LEGACY_PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE
] as const;

const SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPE_SET = new Set<string>([
  ...SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPES,
  ...LEGACY_SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPES
]);

const SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPE_SET = new Set<string>([
  ...SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPES,
  ...LEGACY_SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPES
]);

const SERVICE_WEBVIEW_BRIDGE_CANONICAL_TYPE_ALIASES = new Map<string, string>([
  [SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE, SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE],
  [LEGACY_SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE, SERVICE_WEBVIEW_BRIDGE_DEBUG_TYPE],
  [AGENT_APP_CLIPBOARD_REQUEST_TYPE, AGENT_APP_CLIPBOARD_REQUEST_TYPE],
  [LEGACY_AGENT_APP_CLIPBOARD_REQUEST_TYPE, AGENT_APP_CLIPBOARD_REQUEST_TYPE],
  [AGENT_APP_CLIPBOARD_RESPONSE_TYPE, AGENT_APP_CLIPBOARD_RESPONSE_TYPE],
  [LEGACY_AGENT_APP_CLIPBOARD_RESPONSE_TYPE, AGENT_APP_CLIPBOARD_RESPONSE_TYPE],
  [DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE, DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE],
  [LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE, DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE],
  [DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE, DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE],
  [LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE, DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE],
  [DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE, DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE],
  [LEGACY_DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE, DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE],
  [DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE, DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE],
  [LEGACY_DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE, DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE],
  [DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE, DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE],
  [LEGACY_DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE, DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE],
  [DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE, DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE],
  [LEGACY_DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE, DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE],
  [DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE, DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE],
  [LEGACY_DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE, DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE],
  [DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE, DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE],
  [LEGACY_DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE, DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE],
  [PLUGIN_SETTINGS_READ_REQUEST_TYPE, PLUGIN_SETTINGS_READ_REQUEST_TYPE],
  [LEGACY_PLUGIN_SETTINGS_READ_REQUEST_TYPE, PLUGIN_SETTINGS_READ_REQUEST_TYPE],
  [PLUGIN_SETTINGS_READ_RESPONSE_TYPE, PLUGIN_SETTINGS_READ_RESPONSE_TYPE],
  [LEGACY_PLUGIN_SETTINGS_READ_RESPONSE_TYPE, PLUGIN_SETTINGS_READ_RESPONSE_TYPE],
  [PLUGIN_SETTINGS_WRITE_REQUEST_TYPE, PLUGIN_SETTINGS_WRITE_REQUEST_TYPE],
  [LEGACY_PLUGIN_SETTINGS_WRITE_REQUEST_TYPE, PLUGIN_SETTINGS_WRITE_REQUEST_TYPE],
  [PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE, PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE],
  [LEGACY_PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE, PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE]
]);

const SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPE_BY_REQUEST_TYPE = new Map<string, string>([
  [AGENT_APP_CLIPBOARD_REQUEST_TYPE, AGENT_APP_CLIPBOARD_RESPONSE_TYPE],
  [LEGACY_AGENT_APP_CLIPBOARD_REQUEST_TYPE, LEGACY_AGENT_APP_CLIPBOARD_RESPONSE_TYPE],
  [DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE, DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE],
  [LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_REQUEST_TYPE, LEGACY_DESKTOP_DIALOG_SELECT_DIRECTORY_RESPONSE_TYPE],
  [DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE, DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE],
  [LEGACY_DESKTOP_SHELL_OPEN_PATH_REQUEST_TYPE, LEGACY_DESKTOP_SHELL_OPEN_PATH_RESPONSE_TYPE],
  [DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE, DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE],
  [LEGACY_DESKTOP_DOWNLOAD_FILE_REQUEST_TYPE, LEGACY_DESKTOP_DOWNLOAD_FILE_RESPONSE_TYPE],
  [DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE, DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE],
  [LEGACY_DESKTOP_SCREENSHOT_CAPTURE_REQUEST_TYPE, LEGACY_DESKTOP_SCREENSHOT_CAPTURE_RESPONSE_TYPE],
  [PLUGIN_SETTINGS_READ_REQUEST_TYPE, PLUGIN_SETTINGS_READ_RESPONSE_TYPE],
  [LEGACY_PLUGIN_SETTINGS_READ_REQUEST_TYPE, LEGACY_PLUGIN_SETTINGS_READ_RESPONSE_TYPE],
  [PLUGIN_SETTINGS_WRITE_REQUEST_TYPE, PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE],
  [LEGACY_PLUGIN_SETTINGS_WRITE_REQUEST_TYPE, LEGACY_PLUGIN_SETTINGS_WRITE_RESPONSE_TYPE]
]);

export function isServiceWebviewBridgeRequestType(type: string | undefined | null) {
  return Boolean(type && SERVICE_WEBVIEW_BRIDGE_REQUEST_TYPE_SET.has(type));
}

export function isServiceWebviewBridgeResponseType(type: string | undefined | null) {
  return Boolean(type && SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPE_SET.has(type));
}

export function isServiceWebviewBridgeMessageType(
  type: string | undefined | null,
  canonicalType: string
) {
  if (!type) {
    return false;
  }
  return type === canonicalType || SERVICE_WEBVIEW_BRIDGE_CANONICAL_TYPE_ALIASES.get(type) === canonicalType;
}

export function resolveServiceWebviewBridgeResponseType(requestType: string | undefined | null, fallbackType: string) {
  return requestType ? SERVICE_WEBVIEW_BRIDGE_RESPONSE_TYPE_BY_REQUEST_TYPE.get(requestType) ?? fallbackType : fallbackType;
}

export type ServiceWebviewBridgeReservedCapability =
  | "media.microphone"
  | "media.camera"
  | "screen.capture"
  | "notification";

export type ServiceWebviewBridgeMessage = {
  type?: string;
  requestId?: string;
  action?: string;
  reason?: "missing" | "unauthorized" | "initial" | "navigation" | "route-sync";
  ok?: boolean;
  mode?: "directory";
  text?: string;
  path?: string;
  filename?: string;
  mimeType?: string;
  dataBase64?: string;
  width?: number;
  height?: number;
  sizeBytes?: number;
  cancelled?: boolean;
  values?: Record<string, unknown>;
  defaults?: Record<string, unknown>;
  schema?: unknown;
  shortcutStatuses?: unknown;
  restartRequired?: boolean;
  changedKeys?: string[];
  token?: string | null;
  desktop?: unknown;
  stage?: string;
  message?: string;
  url?: string;
  origin?: string;
  pathname?: string;
  search?: string;
  hash?: string;
};
