import { type App, type BrowserWindow, type WebContents } from "electron";
import { type ServicesFacade } from "../modules/services";
import { type WebsFacade } from "../modules/webs";
import { type ConversationShareFacade } from "../modules/conversation-share";
import { type DesktopPageContextSnapshot, type CopilotDevToolsTarget } from "../../shared/contracts";
import { type AssistantBridgeRuntime, type AssistantRunWakeLock } from "../modules/assistant";
import { type LogsRuntime } from "../support/logging/runtime";
import { type DesktopPetRuntime } from "../modules/pet";
import { type BrowserSurfaceRegistry } from "../modules/web-surfaces";
import { type EnterpriseChatRuntime } from "../modules/enterprise-chat";

export const PLATFORM_DOCUMENT_REVISION_HEADER = "X-Document-Revision";

export type MainIpcRegistrationOptions = {
  app: App;
  issueAgentAccessToken: (app: App, reason: "missing" | "unauthorized") => Promise<any>;
  servicesFacade: ServicesFacade;
  websFacade: WebsFacade;
  conversationShareFacade: ConversationShareFacade;
  ipcMain: any;
  platform: NodeJS.Platform;
  shell: any;
  session: any;
  nativeTheme: any;
  getMainWindow: () => BrowserWindow | null;
  getCurrentPageSnapshot: () => DesktopPageContextSnapshot | null;
  setCurrentPageSnapshot: (snapshot: DesktopPageContextSnapshot | null) => void;
  getCopilotDevToolsTarget: () => CopilotDevToolsTarget | null;
  setCopilotDevToolsTarget: (target: CopilotDevToolsTarget | null) => void;
  getWebContentsById: (id: number) => WebContents | undefined;
  setWorkPanelFullscreenActive: (active: boolean) => void;
  assistantBridgeRuntime: AssistantBridgeRuntime;
  assistantRunWakeLock: AssistantRunWakeLock;
  logsRuntime: LogsRuntime;
  petRuntime: DesktopPetRuntime;
  browserSurfaces: BrowserSurfaceRegistry;
  isTrustedAgentWebclientSession: (sender: WebContents) => boolean;
  enterpriseChatRuntime: EnterpriseChatRuntime;
  desktopSsoController: any;
  startupRestoreController: any;
  desktopAppInfo: any;
  oldRootDecisionRef: { current: "migrate" | "keep" | "cancel" | undefined };
  isFirstDesktopInstall: boolean;
  bundledEnvZipExistsAtStartup: boolean;
  runtimeRootExistedAtStartup: boolean;
  runtimeRootAtProcessStart: string;
  showFileDialog: (...args: any[]) => Promise<any>;
  showSaveDialog: (...args: any[]) => Promise<any>;
  showMessageBox: (...args: any[]) => Promise<any>;
  showArchiveDialog: (...args: any[]) => Promise<any>;
  openLogViewerWindow: (...args: any[]) => Promise<any>;
  closeLogViewerWindow: (...args: any[]) => unknown;
  minimizeLogViewerWindow: (...args: any[]) => unknown;
  maximizeLogViewerWindow: (...args: any[]) => unknown;
  openAgentPlatformMonitorWindow: (...args: any[]) => Promise<any>;
  openAgentRealtimeInspectorWindow: (...args: any[]) => Promise<any>;
  openDesktopActionWorkbenchWindow: (...args: any[]) => Promise<any> | any;
  closeDesktopActionWorkbenchWindow: (...args: any[]) => Promise<any> | any;
  revealPathInFileManager: (...args: any[]) => Promise<any>;
  getServiceWebviewPreloadPath: () => string;
  getServiceWebviewPreloadUrl: () => string;
  runServiceMutation: <T>(task: () => Promise<T>) => Promise<T>;
  handleServiceStart: (serviceId: any) => Promise<any>;
  refreshPluginDesktopGlobalShortcuts: () => unknown;
  notifyServicesChanged: () => void;
  onStartupPreparationSucceeded: () => void;
  onStartupPreparationBlocked: () => void;
  refreshDesktopRuntimeConfigFromCanonicalFiles: (reason: string) => void;
  buildApplicationMenu: () => void;
  refreshTrayContextMenu: () => void;
  refreshMainWindowAppearance: () => void;
  setGlobalSearchOverlayVisible: (visible: boolean) => void;
  setWebviewModalOverlayVisible: (sourceId: string, visible: boolean) => void;
  emitLocaleChanged: (...args: any[]) => unknown;
  captureDesktopScreenshotForWebview: () => Promise<any> | any;
  reportRendererDiagnostic: (...args: any[]) => unknown;
  emitAssistantAttachmentProgress: (...args: any[]) => unknown;
  captureAssistantScreenshot: (...args: any[]) => unknown;
  consumeFirstInstallBootstrapNavigation: () => { shouldOpen: boolean };
};
